<?xml version="1.0" encoding="UTF-8"?>
<testrun name="Ocr" project="Ocr" tests="11" started="2" failures="0" errors="1" ignored="0">
  <testsuite name="SolveOcrTest" incomplete="true">
    <testcase name="testDivideNinePeacesNull" classname="SolveOcrTest" time="28.436">
      <error>java.lang.ArrayIndexOutOfBoundsException: 9
	at SolveOcr.divideNinePeaces(SolveOcr.java:8)
	at SolveOcrTest.testDivideNinePeacesNull(SolveOcrTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
    <testcase name="testDivideNinePeacesSize" classname="SolveOcrTest" incomplete="true"/>
    <testcase name="testDivideNinePeaces" classname="SolveOcrTest" incomplete="true"/>
  </testsuite>
  <testsuite name="PossibleNumbersTest" incomplete="true">
    <testcase name="testConstructor" classname="PossibleNumbersTest" incomplete="true"/>
    <testcase name="testConstructorWithNumbersNull" classname="PossibleNumbersTest" incomplete="true"/>
    <testcase name="testConstructorWithNumbers" classname="PossibleNumbersTest" incomplete="true"/>
    <testcase name="testMethodRemoveNumber" classname="PossibleNumbersTest" incomplete="true"/>
    <testcase name="testMethodRemoveTwoNumbers" classname="PossibleNumbersTest" incomplete="true"/>
    <testcase name="testMethodCheckFalse" classname="PossibleNumbersTest" incomplete="true"/>
    <testcase name="testMethodCheckTrue" classname="PossibleNumbersTest" incomplete="true"/>
  </testsuite>
  <testsuite name="ReaderOcrTest" incomplete="true">
    <testcase name="testMethodReader" classname="ReaderOcrTest" incomplete="true"/>
  </testsuite>
</testrun>
